---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - net.dummy.com
  resources:
  - gatewayclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.dummy.com
  resources:
  - gatewayclasses/finalizers
  verbs:
  - update
- apiGroups:
  - net.dummy.com
  resources:
  - gatewayclasses/status
  verbs:
  - get
  - patch
  - update
